eclipse-zenoh/zenoh-plugin-dds

- README.md
The current build instructions fail if using the default stable release of Rust installed by rustup due to the use of some unstable features:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
--> /home/spiderkeys/.cargo/git/checkouts/zenoh-cc237f2570fab813/12bfe92/zenoh-router/src/lib.rs:14:1
|
14 | #![feature(get_mut_unchecked)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0554]: `#![feature]` may not be used on the stable release channel
--> /home/spiderkeys/.cargo/git/checkouts/zenoh-cc237f2570fab813/12bfe92/zenoh-router/src/lib.rs:15:1
|
15 | #![feature(async_closure)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0554]: `#![feature]` may not be used on the stable release channel
--> /home/spiderkeys/.cargo/git/checkouts/zenoh-cc237f2570fab813/12bfe92/zenoh-router/src/lib. …
```
> Add note to README to use Rust nightly

- .github/workflows/dockerhub.yml
I would like to propose that a multiarch docker image be hosted on the dockerhub. 
This PR contains a github action to do that, but requires a few changes to be hosted in the correct dockerhub organization.
To test the PR as it stands right now (right now it is on my personal dockerhub acct)
`docker run --network=host vinnnyr/zenoh-plugin-dds` 
This will work on both `arm` and `x86` type machines. 
- Repo maintainers should add their `DOCKERHUB.USERNAME` and their `DOCKERHUB.TOKEN` to the repo secrets using the Github secrets portion
- We must change the line so that it matches the correct dockerhub repo / tag the maintainers would like to use.
> Add Multiarch docker build to github actions

- .gitignore
- README.md
- zenoh-bridge-dds/Cargo.lock
- zenoh-bridge-dds/src/main.rs
- zplugin-dds/Cargo.lock
- zplugin-dds/Cargo.toml
- zplugin-dds/src/dds_mgt.rs
- zplugin-dds/src/lib.rs
- zplugin-dds/src/qos.rs
- zplugin-dds/src/ros_discovery.rs
This PR adds a **`--fwd-discovery`** option that activates a mode where:
- on discovery of a local DDS reader or writer, the bridge forwards via zenoh this discovery information to the remote bridges
- when receiving a discovery information via zenoh from a remote bridge, the bridge creates a similar _"serving"_ DDS reader or writer (same QoS), and route to/from zenoh for this entity
- on reception of a DDS publication on `ros_discovery_info` topic, the bridge forwards it via zenoh to the remote bridges
- when reception a `ros_discovery_info` data via zenoh, a bridge converts all the original GIDs to their equivalent GIDs for the created routes (i.e. the _"serving"_ DDS reader or writer for the route)
- on un-discovery, or on the detection of the leaving or crash of a remote bridge, all …
> Implement DDS discovery forwarding mode (#33)

- Cargo.lock
- EXAMPLE_CONFIG.json5
- README.md
- zenoh-bridge-dds/Cargo.toml
- zenoh-bridge-dds/src/main.rs
- zplugin-dds/src/config.rs
- zplugin-dds/src/lib.rs
- Adds a `-c, --config <file>` option to `zenoh-bridge-dds`
- Documents this configuration file
- Update the behaviour of the command line arguments to override their equivalent in the config file
> Add support of a configuration file

- Cargo.lock
- zplugin-dds/src/lib.rs
On a query on `/@/**` the `zenoh-bridge-dds` returns keys with `null`as values.
The cause is eclipse-zenoh/zenoh#216. This PR updates zenoh to benefit its fix.
> Fix admin-space returning 'null' values

- zplugin-dds/src/lib.rs
Fix a bug that was introduced in 5941e9bf76 : 
in forward discovery mode, the parsing of paths used to forward the discovery information was incorrect at reception.
This was leading to wrong admin paths in route's `remote_routed_writers`/`remote_routed_readers` lists, and consequently to the inability to correctly cleanup the routes and entities when a remote bridge leaves.
> Fix parsing of fwd discovery path

- Cargo.lock
- zenoh-bridge-dds/Cargo.toml
- zenoh-bridge-dds/src/main.rs
Add a `--watchdog=[Period]` option to `zenoh-bridge-dds` (default period is 1 second).
Setting this option makes the `zenoh-bridge-dds` to spawn an extra thread that wakes up every `period` and uses a [LivelinessMonitor](https://github.com/p-avital/liveliness-monitor) to check if the async scheduler did not spend too much time not scheduling any task.
It logs messages depending the elapsed time since the last scheduled task:
- at `error` level if elapsed time > `period`
- at `warn` level if elapsed time > `100 ms`
- at `info` level if elapsed time > `10 ms`
> Add a watchdog of tasks scheduling

- DEFAULT_CONFIG.json5
- README.md
- zenoh-bridge-dds/src/main.rs
- zplugin-dds/src/config.rs
- zplugin-dds/src/lib.rs
- zplugin-dds/src/route_zenoh_dds.rs
Add a `--queries-timeout` option to `zenoh-bridge-dds` and a `queries_timeout` attribute to the JSON config.
This option is a duration in seconds (default value 5.0 sec).
It allows to configure the timeout for all queries made by the bridge to another bridge:
- query of historical publications from TRANSIENT_LOCAL DDS Writers
- in forwarding mode, query of discovery information from remote bridge
> Add --queries-timeout option

- zplugin-dds/src/lib.rs
Using the `--dds-localhost-only` this warning is displayed by CycloneDDS 0.10:
`1675348590.824894 [0] async-std/: config: //CycloneDDS/Domain/General: 'NetworkInterfaceAddress': deprecated element (CYCLONEDDS_URI+0 line 1)``
This PR updates the CycloneDDS configuration used with this option to latest syntax:
`<CycloneDDS><Domain><General><Interfaces><NetworkInterface address="127.0.0.1" multicast="true"/></Interfaces></General></Domain></CycloneDDS>`
NOTE: force `multicast="true"` since multicast is always working on localhost, even if on some Ubuntu the MULTICAST flag is not set for this interface. See https://github.com/eclipse-cyclonedds/cyclonedds/issues/1400#issuecomment-1241575011
> Fix CycloneDDS warning 'NetworkInterfaceAddress: deprecated element'

- DEFAULT_CONFIG.json5
- zplugin-dds/src/config.rs
#119 was breaking backward compatibility requiring in JSON5 config files a sequence of strings for `allow` and `deny` options, while former version was expecting a single string.
This PR updates the parsing of those options to accept either a single string, either a sequence of strings (that are concatenated with `|` to create a Regex).
> Accept single string for allow/deny option

- zplugin-dds/src/route_zenoh_dds.rs
This PR makes the CycloneDDS `sertype` for a topic to be computed only once at route creation, rather than at each DDS write.
> Optimisation in Zenoh to DDS route

- zenoh-bridge-dds/src/main.rs
`block_on` on a pending future will steal the thread from the executor.
Better awaiting and the pending future instead.
> Remove unnecessary block_on

- zenoh-plugin-dds/src/dds_mgt.rs
This PR modifies the formatting of the sample payload in trace logging to be lowercase hexadecimal rather than decimal. This is to ensure consistency within the application as Zenoh payloads received across the bridge are logged in hexadecimal format.
> Modified formatting of sample payload in trace logs

- CMakeLists.txt
After running ROS 2 colcon build, the binary (zenoh-bridge-dds) is put under `install/zenoh_bridge_dds/lib/` folder, which can not be used directly when we source `install/setup.bash`
I move the binary to `install/zenoh_bridge_dds/bin/` and also rename the binary name to zenoh-bridge-dds (The same name if we build with `cargo build`).
> Put binary "zenoh-bridge-dds" into bin folder while colcon build

- Cargo.lock
- zenoh-plugin-dds/src/dds_mgt.rs
The implementation now serializes raw samples when received via an Iceoryx buffer before forwarding it onto Zenoh. This ensures onward applications receive samples in a consistent format.
This is currently a draft PR as this requires an update to Cyclors in order to compile: https://github.com/kydos/cyclors/pull/15
> Corrected handling of Iceoryx buffer content

- Cargo.lock
Default Qos values are now represented as None in Qos struct.
> Update Cyclors to latest version for Qos changes.

- zenoh-plugin-dds/src/lib.rs
This makes the bridge to follow the same behaviour than ROS 2 with `rmw_cyclonedds_cpp` when `ROS_LOCALHOST_ONLY=1`: just make CycloneDDS to use `127.0.0.1` not forcing `multicast=true`, and thus avoiding discovery issue with ROS Nodes that don't force multicast usage.
See https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/issues/12#issuecomment-1792248458 for more details.
> When ROS_LOCALHOST_ONLY=1 don't force multicast on lo (fix #158)

- .github/workflows/release.yml
Fix typo when packaging the plugin for Windows (`zenoh-plugin*.dll` -> `zenoh_plugin*.dll`)
> Release action: fix Windows packaging (fix #156)

- README.md
- zenoh-plugin-dds/src/lib.rs
A new Zenoh plugin dedicated for ROS 2 has been developed:
https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds
We strongly advise ROS 2 users to use it, since it better integrates with ROS 2 and brings these benefits:
- Better integration of the **ROS graph** (all ROS topics/services/actions can be seen across bridges)
- Better support of **ROS toolings** (ros2 CLI, rviz2...)
- Configuration of a **ROS namespace** on the bridge (instead of on each ROS Node)
- Services and Action as **Zenoh Queryables** with more efficiency and scalability that RPC over DDS
- Even more **compact discovery information** between the bridges (not forwarding all `ros_discovery_info` messages as such)
The Zenoh plugin for DDS will eventually be deprecated for ROS 2 usage.
> Encourage ros2dds bridge usage for ROS 2

- zenoh-plugin-dds/src/dds_mgt.rs
- zenoh-plugin-dds/src/lib.rs
At Writer creation, just remove Reliability QoS if set to BEST_EFFORT.
If not set, the default Reliability value for Writers is RELIABLE with max_blocking_time=100ms.
> Always create RELIABLE Writers (fix #165)

- README.md
- zenoh-plugin-dds/src/lib.rs
The plugin had its admin space under `@/service/<uuid>/dds/**`.
The main drawback is that it's mixed with Zenoh's admin space which is prefixed with `@/`.
For separation of concerns and for coherency with the plugin for ROS2 which uses `@ros2/<uuid>` as prefix, this PR changes the admin prefix for DDS plugin to `@dds/<uuid>`
Migration guide:
- `@/service/<uuid>/dds/version` becomes:
`@dds/<uuid>/version`
- `@/service/<uuid>/dds/config` becomes:
`@dds/<uuid>/config`
- `@/service/<uuid>/dds/participant/<gid>/reader/<gid>/<topic>` becomes:
`@dds/<uuid>/participant/<gid>/reader/<gid>/<topic>`
- `@/service/<uuid>/dds/participant/<gid>/writer/<gid>/<topic>` becomes:
`@dds/<uuid>/participant/<gid>/writer/<gid>/<topic>`
- `@/service/<uuid>/dds/route/from_dds/<zenoh-resource>` becomes: …
> Admin space: change prefix from '@/service/<uuid>/dds' to '@dds/<uuid>'

- zenoh-plugin-dds/Cargo.toml
- zenoh-plugin-dds/src/lib.rs
As suggested by @milyin this PR renames the `no_mangle` feature to `dynamic_plugin` which is easier to understand.
- Sister of: https://github.com/eclipse-zenoh/zenoh/pull/1010
> chore: renamed no_mangle feature to dynamic_plugin

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- Cargo.lock
- Cargo.toml
- zenoh-bridge-dds/src/main.rs
- zenoh-plugin-dds/src/config.rs
- zenoh-plugin-dds/src/dds_mgt.rs
- zenoh-plugin-dds/src/lib.rs
- zenoh-plugin-dds/src/ros_discovery.rs
- zenoh-plugin-dds/src/route_dds_zenoh.rs
- zenoh-plugin-dds/src/route_zenoh_dds.rs
see https://github.com/eclipse-zenoh/zenoh/pull/1193
> chore: bump zenoh version

- DEFAULT_CONFIG.json5
Apply Julien's suggestion of the description in config
https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/pull/220#discussion_r1728946937
> Update config description for async runtime.

- Cargo.lock
- zenoh-plugin-dds/src/route_dds_zenoh.rs
Move zenoh::pubsub::Reliability to zenoh::qos::Reliability. To be merged after https://github.com/eclipse-zenoh/zenoh/pull/1457.
> Align Rust with Reliability exported in zenoh::qos

- Cargo.lock
- Cargo.toml
- zenoh-plugin-dds/src/lib.rs
- zenoh-plugin-dds/src/route_zenoh_dds.rs
DDS plugin update for new serialization api  
https://github.com/eclipse-zenoh/zenoh/issues/1474
Note: update Dependencies when https://github.com/eclipse-zenoh/zenoh/pull/1473 is merged
> new serializer API Update

- .github/workflows/release.yml
This way for scheduled events the input will be correctly set.
See https://github.com/eclipse-zenoh/zenoh-plugin-dds/actions/runs/13935976471/job/39003823235
> fix: set bump-deps-pattern to default to zenoh.*

- zenoh-plugin-dds/src/qos_helpers.rs
Revert a change from #449 which was not compatible with Rust 1.75.
[`std::option::Option::is_none_or()`](https://doc.rust-lang.org/nightly/std/option/enum.Option.html#method.is_none_or) was introduced since Rust 1.82.
> Fix build with Rust 1.75

- .github/workflows/release.yml
GITHUB_OUTPUT requires EOF delimiter for multiline strings.
See https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#example-of-a-multiline-string
Fix https://github.com/eclipse-zenoh/zenoh-plugin-dds/actions/runs/18276123122/job/52028559731
> ci: fix release workflow multiline inputs
