eclipse-zenoh/zenoh-plugin-dds

- README.md
changed ". ./configure.sh" to "./config.sh"
> changed configure.sh to config.sh

- Cargo.lock
- zenoh-bridge-dds/Cargo.toml
- zplugin-dds/Cargo.toml
@JEnoch Can you merge eclipse-zenoh/plugins-refactor into master after merging this PR ? Thanks :)
> Plugins refactor

- EXAMPLE_CONFIG.json5
- README.md
- zenoh-bridge-dds/src/main.rs
- zplugin-dds/src/config.rs
- zplugin-dds/src/lib.rs
> Add 'deny' config (and --deny option)

- Cargo.lock
- zenoh-bridge-dds/Cargo.toml
- zenoh-bridge-dds/src/main.rs
- zplugin-dds/Cargo.toml
Sister PR for eclipse-zenoh/zenoh#214
> Sister PR for eclipse-zenoh/zenoh#214

- zplugin-dds/src/dds_mgt.rs
- zplugin-dds/src/lib.rs
- zplugin-dds/src/ros_discovery.rs
... and replace with a correct error management with logs.
> Remove unwraps that may cause panic/crash at runtime

- DEFAULT_CONFIG.json5
- README.md
Similar to https://github.com/eclipse-zenoh/zenoh/pull/339
> EXAMPLE_CONFIG.json5 -> DEFAULT_CONFIG.json5

- Cargo.lock
- Cargo.toml
- zenoh-bridge-dds/Cargo.toml
- zplugin-dds/Cargo.toml
This is a preparatory PR.
It will be merged once https://github.com/eclipse-zenoh/zenoh/pull/347 is merged and `Cargo.lock` is synced.
> Point to master branch

- Cargo.lock
- zplugin-dds/Cargo.toml
- zplugin-dds/src/dds_mgt.rs
- zplugin-dds/src/lib.rs
- zplugin-dds/src/route_dds_zenoh.rs
- zplugin-dds/src/route_zenoh_dds.rs
This PR implements the solution described in https://github.com/eclipse-zenoh/zenoh-plugin-dds/issues/102#issuecomment-1323507672 .
> In -f mode, create a local zenoh sub on DDS Reader discovery (fix #102)

- zplugin-dds/src/dds_mgt.rs
This PR calls synchronous `put()` on Zenoh rather than start blocking tasks to do asynchronous `put()` (that was the only API at this time...)
> Optimisation in DDS to Zenoh route

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- zenoh-plugin-dds/src/dds_mgt.rs
- zenoh-plugin-dds/src/ros_discovery.rs
- zenoh-plugin-dds/src/route_zenoh_dds.rs
> Resolves #143 by fixing build to work with latest master version of Cyclors.

- zenoh-plugin-dds/src/config.rs
[Context](https://github.com/eclipse-zenoh/zenoh-plugin-webserver/pull/25#issuecomment-1824448225).
> Fix `__path__` and `__required__` types in `Config`

- zenoh-plugin-dds/Cargo.toml
See https://github.com/eclipse-zenoh/zenoh/pull/640.
> Fix Debian package for `0.10.1-rc`

- Cargo.lock
- Cargo.toml
- README.md
- fix: Rename master -> main in manifest & README
- chore: Update lockfile
> Fix zenoh git location

- .github/workflows/release.yml
- zenoh-bridge-dds/Cargo.toml
[See this workflow run.](https://github.com/eclipse-zenoh/zenoh-plugin-dds/actions/runs/8608265542)
> fix: Release workflow

- Cargo.toml
> Changed the cyclors dependency to be taken from a release.

- Cargo.lock
- Cargo.toml
- zenoh-bridge-dds/src/main.rs
- zenoh-plugin-dds/src/lib.rs
Target zenoh branch to be updated and merged after https://github.com/eclipse-zenoh/zenoh/pull/953
> Port to new plugin loading system

- zenoh-bridge-dds/.deb/postrm
- zenoh-bridge-dds/.service/zenoh-bridge-dds.service
- zenoh-bridge-dds/Cargo.toml
Sister pull request of https://github.com/eclipse-zenoh/zenoh-plugin-mqtt/pull/85.
> Fix Debian package

- Cargo.lock
- DEFAULT_CONFIG.json5
Update Cargo.lock
Squashed commit of the following:
commit 394287c61384b55d583b1636397240d81aaa6be4
Author: eclipse-zenoh-bot <61247838+eclipse-zenoh-bot@users.noreply.github.com>
Date:   Tue Jul 30 02:28:46 2024 +0200
build: Sync  with eclipse-zenoh/zenoh@2d88c7b from 2024-07-29 (#286)
Co-authored-by: eclipse-zenoh-bot <eclipse-zenoh-bot@users.noreply.github.com>
commit cd3d0fd9f4857b26dd9d3a1416f7b5193d62f63a
Author: eclipse-zenoh-bot <61247838+eclipse-zenoh-bot@users.noreply.github.com>
Date:   Sat Jul 27 02:28:35 2024 +0200
build: Sync  with eclipse-zenoh/zenoh@e587aa9 from 2024-07-26 (#285)
Co-authored-by: eclipse-zenoh-bot <eclipse-zenoh-bot@users.noreply.github.com>
commit ce1cf638eb81140c7ab3c089970a0b24ffff1072
Author: eclipse-zenoh-bot …
> Merge main -> dev/1.0.0,

- Cargo.lock
- Cargo.toml
- zenoh-bridge-dds/src/main.rs
Sister of: https://github.com/eclipse-zenoh/zenoh/pull/1415
> deps: align zenoh #1415

- zenoh-plugin-dds/src/route_zenoh_dds.rs
> Updated Zenoh subscriber declaration to undeclare subscribers when references are dropped.

- Cargo.lock
- zenoh-plugin-dds/src/lib.rs
> Sync lockfile with Zenoh `3740564` from `2024-10-08`

- Cargo.lock
- zenoh-plugin-dds/src/lib.rs
- zenoh-plugin-dds/src/route_dds_zenoh.rs
- zenoh-plugin-dds/src/route_zenoh_dds.rs
compatibility with api changes due to namespace introduction
> compatibility with api changes due to namespace introduction

- rust-toolchain.toml
- zenoh-plugin-dds/src/dds_mgt.rs
- zenoh-plugin-dds/src/qos_helpers.rs
- zenoh-plugin-dds/src/route_zenoh_dds.rs
Depends on https://github.com/eclipse-zenoh/zenoh/pull/1803
> Bump Rust toolchain to 1.85

- zenoh-plugin-dds/src/lib.rs
> Create matching DDS entity with correct partition Qos.

- .github/workflows/ci.yml
- zenoh-plugin-dds/src/lib.rs
Fixed clippy warning inline with other similar warnings. Also modified CI to ensure clippy is run correctly.
> Fix clippy warning

- Cargo.lock
- Cargo.toml
> Fix segmentation fault when paired with RTI Persistence Service and Dispose on Keyed Objects

- .github/workflows/release.yml
https://github.com/eclipse-zenoh/zenoh-plugin-dds/actions/runs/18274119151/job/52022209755
> ci: fix wrong quotes in compute version

- Cargo.toml
fix name for zenoh pinned deps and formatting
> ci: update zenoh-pinned-deps-1-75
